version: "3"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fc_city_service
    networks:
      - dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - dev

networks:
  dev:

volumes:
  pgdata:
